spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/plants_support?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

server:
  port: 8080

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  paths-to-match: /api/**

openapi:
  service:
    api-docs: api-service
    server: http://localhost:${server.port}
    title: API Document
    version: 1.0.0

# AI Configuration
openai:
  api:
    key: ${OPENAI_API_KEY:temp-key-for-testing}

openrouter:
  api:
    key: ${OPENROUTER_API_KEY}
    base-url: https://openrouter.ai/api/v1
    model: openai/gpt-3.5-turbo

# Payment Configuration
paypal:
  client:
    id: ${PAYPAL_CLIENT_ID:temp-paypal-id}
    secret: ${PAYPAL_CLIENT_SECRET:temp-paypal-secret}
  mode: sandbox

# VNPAY Configuration
vnpay:
  tmn-code: IZVMM9RJ
  hash-secret: 0PS4G1NU0ZOFUGWQLHNZTFVLWT23RAJQ
  payment-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: http://localhost:8080/api/payment/vnpay-return
  ipn-url: http://localhost:8080/api/payment/vnpay-ipn
  merchant-admin-url: https://sandbox.vnpayment.vn/merchantv2/