name: Deploy to Azure VM

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Build with Maven
      run: |
        cd plantcare-backend
        mvn clean package -DskipTests
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: plantcare-app
        path: plantcare-backend/target/*.jar
        
    - name: Deploy to Azure VM
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.AZURE_HOST }}
        username: ${{ secrets.AZURE_USERNAME }}
        key: ${{ secrets.AZURE_PRIVATE_KEY }}
        port: 22
        script: |
          # Stop existing application
          sudo systemctl stop plantcare-app || true
          
          # Create app directory if not exists
          sudo mkdir -p /opt/plantcare-app
          
          # Download artifact
          cd /opt/plantcare-app
          rm -f plantcare-app.jar
          
          # Wait for artifact to be available
          sleep 10
          
          # Start application
          sudo systemctl start plantcare-app
          
          # Check status
          sudo systemctl status plantcare-app 